# Site settings
title: ItsBeenJamied
email: jamiehdavis96@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  ItsBEenJamied
url: http://blog.itsbeenjamied.co.uk" # the base hostname & protocol for your site
twitter_username: jamieharrydavis
github_username:  jamiedavis2016
encoding: utf-8

# Build settings
# markdown: redcarpet
# highlighter: pygments
# extensions: [tables fenced_code_blocks]

exclude: [vendor]
kramdown:
   input: GFM
gems:
  - jekyll-sitemap