#title: JD's BlogSite
email: jamiehdavis96@gmail.com
description: Technology based blog on my personal opinion on topics and projects, Jamie Davis tech blog
baseurl: ""
url: ""
#baseurl: "/BlogSite" # the subpath of your site, e.g. /blog
#url: "https://jamiedavis2016.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  JamieDavis2016

defaults:
- scope:
    path: ''
    type: posts
    sidebar: "main "
  values:
    layout: single
    author_profile: true
    read_time: true
    comments: true
    share: true
    related: true
    sidebar: "main"
- scope:
    path: ''
    type: pages
  values:
    layout: home
    author_profile: true
    sidebar: "main"

author:
  name: "Jamie Davis"
  avatar: "/assets/images/capture.png"
  bio: "I am a software developer with a passion for technology"
  location: "London, United Kingdom"
  github: JamieDavis2016
  reddit: Jamie-Davis
  email: jamiehdavis96@gmail.com
markdown: kramdown
#theme: minimal-mistakes-jekyll

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-remote-theme
remote_theme: "mmistakes/minimal-mistakes"
repository:
paginate: 10
paginate_path: /path:num/