# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

#title: JD's BlogSite
email: jamiehdavis96@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

defaults:
- scope:
    path: ''
    type: posts
    sidebar: "main "
  values:
    layout: single
    author_profile: true
    read_time: true
    comments: true
    share: true
    related: true
    sidebar: "main"
- scope:
    path: ''
    type: pages
  values:
    layout: home
    author_profile: true
    sidebar: "main"



author:
  name: "Jamie Davis"
  avatar: "/assets/images/capture.png"
  bio: "I am a software developer with a passion for technology"
  location: "London, United Kingdom"
  github: JamieDavis2016
  reddit: Jamie-Davis
  email: jamiehdavis96@gmail.com

# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed

paginate: 10
paginate_path: /path:num/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
